affiliates_connect_flipkart.settings:
  type: config_object
  label: 'Affiliates Connect Flipkart settings'
  mapping:
    native_api:
      type: boolean
      label: 'Allows usage Affiliate Marketing using tracking ID'
    flipkart_tracking_id:
      type: string
      label: 'Input tracking ID of corresponding Affiliate API'
    flipkart_token:
      type: string
      label: 'Input token of corresponding Affiliate API'
    scraper_api:
      type: boolean
      label: 'Allows usage Scraper API to overcome limitation of Affiliate API'
    data_storage:
      type: boolean
      label: 'Allows storing product data in your site database'
    affiliate_import:
      type: string
      label: 'Import period for Affiliate API'
    scraper_import:
      type: string
      label: 'Import period for Scraper API'
    content_scrape:
      type: boolean
      label: 'Allows to scrape content on a daily basis'
    scrape_timer:
      type: string
      label: 'Import period for content scraping'
    full_content:
      type: boolean
      label: 'Allows scraping of content based on content'
    reviews:
      type: boolean
      label: 'Allows scraping of content based on reviews'
    available:
      type: boolean
      label: 'Allows scraping of content based on availability'
    size:
      type: boolean
      label: 'Allows scraping of content based on size'
    color:
      type: boolean
      label: 'Allows scraping of content based on color'
    offers:
      type: boolean
      label: 'Allows scraping of content based on offers'
    others:
      type: boolean
      label: 'Allows scraping of content based on other criteria'
