<?php

/**
 * @file
 * Contains affiliates_connect_flipkart.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * Main module help for the affiliates_connect_flipkart module.
 */
function affiliates_connect_flipkart_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    case 'help.page.affiliates_connect_flipkart':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Flipkart Plugin') . '</p>';
      return $output;

    default:
  }

}
